version: '3'
services: 
  db:
    image: postgres:latest
    volumes:
      - ./.data/db:/var/lib/postgresql
    restart: always    
    environment:
      POSTGRES_DB: bitbucket
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 

  bitbucket:
    depends_on:
      - db
        #image: cptactionhank/atlassian-bitbucket:latest    
    image: atlassian/bitbucket-server:latest    
    links:
      - db
    ports:
      - "10020:7990"
      - "7999:7999"
    volumes:
      - ./.data/bitbucket:/var/atlassian/application-data/bitbucket
    restart: always    
    environment: 
      JIRA_DB_HOST: db:3306
      JIRA_DB_PASSWORD: 
      JIRA_DB_USER: 
      JIRA_DB_NAME: bitbucket  

