version: '2'
services: 
  db:
    image: postgres:latest
    volumes:
      - "./.data/db:/var/lib/postgresql"
    restart: always    
    environment:
      POSTGRES_DB: bitbucket
      POSTGRES_USER: materliu
      POSTGRES_PASSWORD: bitbucket

  bitbucket:
    depends_on:
      - db
    image: cptactionhank/atlassian-bitbucket:latest    
    links:
      - db
    ports:
      - "10020:7990"
    restart: always    
    environment: 
      JIRA_DB_HOST: db:3306
      JIRA_DB_PASSWORD: bitbucket
      JIRA_DB_USER: materliu
      JIRA_DB_NAME: bitbucket  

